Proposal of convergence tests using temperature and net radiative flux change at the TOA.
atmtools/konrad pull request #141
Opened 2020-09-29 12:22 UTC by diegojco

Added convergence test in terms of the temperature and the net
radiative flux at the TOA. Additions on file `core.py`

1) Added class attributes initialised to `None`: `delta2`, `deltaT` and
   `deltaN` (lines 180,181).

2) Added the test for the net radiative flux at the TOA in the
   class method `is_converged()`.

   The model only converges if both the temperature and net
   radiative flux at TOA fulfill their convergence criteria.

3) Added calculation of the old net radiative flux at the TOA
   (lines 278-291).

4) Added a calculation of a specific convergence threshold for the
   net radiative flux at the TOA (lines 379-383).

5) Added calculation of the net radiative flux change at the TOA
   (lines 385-396).

6) Added logger entries to check the status of the temperature and
   the net radiative flux changes (lines 397-403).

2020-09-30 09:01 UTC, lkluft commented
Thanks for the PR! I will review it in the next few days ;)

2020-10-06 15:48 UTC, lkluft requested changes

2020-10-06 15:48 UTC, lkluft commented on konrad/core.py
> +            return False
You can use boolean algebra
```suggestion
 return temp_test and N_test
```

2020-10-06 15:48 UTC, lkluft commented on konrad/core.py
> +             N = 0
The radiation class provides a convenience variable `self.radiation["toa"]`, which should contain exactly this value.

Also, please indent blocks with [four spaces](https://www.python.org/dev/peps/pep-0008/#indentation).

2020-10-06 15:48 UTC, lkluft commented on konrad/core.py
> +                          )
I am not sure, if I understand your convergence criterion. I though that you want the absolute change in TOA to be smaller than a given delta. But here, you check if it is smaller than the temperature-derivative of black-body radiation.
Could you elaborate on this decision? We can also meet offline and discuss it ;)

2020-10-06 15:48 UTC, lkluft commented on konrad/core.py
> +            if self.logevery is not None and self.niter % self.logevery == 0:
Add some point I should add an `RCE.log()` utility method. But this is merely a comment to myself ;)

2020-10-16 08:42 UTC, diegojco commented
I will close this pull request. I found out that there are some of experiments that will never reach convergence because they oscillate. I need to correct this.

2020-10-16 08:42 UTC, closed without merging